factorGraphEstimator:
  debug: true
  useImuProp: true
  pipeStdout: false
  isamParameters:
    relinearizeThreshold: 0.01
    relinearizeSkip: 1
    enablePartialRelinearizationCheck: false
    cacheLinearizedFactors: false
    enableDetailedResults: true
    findUnusedFactorSlots: false
    gaussianWildfireThreshold : 0.001

  imuFactorParams:
    # general
    useImuFactor: true
    useImuBias: false
    imuBiasIncr: 10
    invertX: false
    invertY: false
    invertZ: false

    # factor specific
    accelNoiseSigma: 1.0
    gyroNoiseSigma: 0.1
    accelBiasRwSigma: 0.1
    gyroBiasRwSigma: 0.1
    integrationErrorCov: 1e-4
    biasAccOmegaInt: 0.1

    # bias noise
    biasNoise: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

  poseFactorParams:
    usePoseFactor: false
    # rad, rad, rad, m, m, m
    poseNoise: [1.0, 1.0, 1.0, 5.0, 5.0, 5.0]
    poseVelNoise: [5.0, 5.0, 5.0]

  cameraConfig:
    # sets the names of the cameras to be registered
    cameraNames: [left_right]

    left_right:
      # fx, fy, s, u0, v0
      K: [602.8772177219314, 602.8880443100697, 0, 628.4051298263508, 373.66555567947336]

      # transform x, y, z, qw, qx, qy, qz
      transform: [0.17, 0.0, 0.0, -0.5, 0.5, -0.5, 0.5]

  arucoFactorParams:
    useArucoFactor: true

    # what cameras we will wait for detections from before creating a state
    enabledCameras: [left_right]

    #rad, rad, rad, m, m, m
    arucoNoise: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

    # error in px
    projectionPixelNoise: 10

    #rad, rad, rad, m, m, m
    arucoPriorNoise: [1.0, 1.0, 1.0]

  projectionFactorParams:
    useProjectionFactor: true
    defaultPixelNoise: 10.0
    pairingThreshold: 0.02 # allowed time stamp difference

    # list of valid objects
    objects: [1, 2, 3, 4]
    objectList:
      1_noise: 10 # top left corner
      2_noise: 10 # top right corner
      3_noise: 10 # bottom right corner
      4_noise: 10 # bottom left corner

    # list of known objects to track, no _ allowed
    trackedObjects: []
    objectPriorNoise: [10.0, 10.0, 10.0]
    # TODO Get the actual prediction
    # Gate#_type#
    objectPriors:
      1_1: [10, 0, 0]

  priorConfig:
    # x, y, z, qw, qx, qy, qz, x_dot, y_dot, z_dot
    initial_state: [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    initial_vel_noise: 0.01
    # rad, rad, rad, m, m, m
    initial_pose_noise: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    initial_bias_noise: 0.1


