factorGraphEstimator:
  debug: true
  useImuProp: true
  isamParameters:
    relinearizeThreshold: 0.01
    relinearizeSkip: 1
    enablePartialRelinearizationCheck: false
    cacheLinearizedFactors: false
    enableDetailedResults: true
    findUnusedFactorSlots: false
    gaussianWildfireThreshold : 0.001

  imuFactorParams:
    # general
    imuDebug: false
    useImuFactor: true
    useImuBias: true
    imuBiasIncr: 3
    invertX: false
    invertY: false
    invertZ: false

    # factor specific
    accelNoiseSigma: 1.0
    gyroNoiseSigma: 0.5
    accelBiasRwSigma: 0.1
    gyroBiasRwSigma: 0.1
    integrationErrorCov: 1e-4
    biasAccOmegaInt: 0.1

    # bias noise
    biasNoise: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

  gpsFactorParams:
    useGpsFactor: true
    gpsToImu: [-0.37, 0.0, -0.06]
    maxGpsError: 5.0
    useFixedOrigin: false

  poseFactorParams:
    usePoseFactor: false
    # rad, rad, rad, m, m, m
    poseNoise: [1.0, 1.0, 1.0, 5.0, 5.0, 5.0]
    poseVelNoise: [5.0, 5.0, 5.0]

  cameraConfig:
    # sets the names of the cameras to be registered
    cameraNames: [left, right]

    pairingThreshold: 0.02

    left:
      # fx, fy, s, u0, v0
      K: [548.4088134765625, 548.4088134765625, 0.0, 512.0, 384.0]

      # x, y, z
      translation: [0.0, 0.0, 0.0]
      # qw, qx, qy, qz
      rotation: [-0.5, 0.5, -0.5, 0.5]

    right:
      # fx, fy, s, u0, v0
      K: [548.4088134765625, 548.4088134765625, 0.0, 512.0, 384.0]

      # x, y, z
      translation: [0.2, 0.0, 0.0]
      # qw, qx, qy, qz
      rotation: [-0.5, 0.5, -0.5, 0.5]

  arucoFactorParams:
    useArucoFactor: false
    useArucoConstraints: false
    useArucoRange: false
    useProjectionDebug: false

    arucoRangeNoise: 10

    # m from corner to corner of aruco
    arucoLength: 0.1

    #rad, rad, rad, m, m, m
    arucoNoise: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

    # error in px
    projectionPixelNoise: 20

    # m, m, m
    arucoPriorNoise: [4.0, 4.0, 4.0]

  projectionFactorParams:
    useProjectionFactor: false
    defaultPixelNoise: 60.0
    gateDistThreshold: 10.0 #maximum distance between two gates allowed to reassign ids

    # list of valid types of objects
    objects: [1, 2, 3, 4]
    objectList:
      1_noise: 30 # top left corner
      2_noise: 30 # top right corner
      3_noise: 30 # bottom right corner
      4_noise: 30 # bottom left corner

    # list of known objects to track, no _ allowed
    trackedObjects: []
    objectPriorNoise: [1.0, 1.0, 0.1]

    # Gate#_type#
    #objectPriors:
    #  1_1: [10, 0, 0]

  priorConfig:
    # x, y, z, qw, qx, qy, qz, x_dot, y_dot, z_dot
    initial_state: [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    initial_vel_noise: 0.01
    # rad, rad, rad, m, m, m
    initial_pose_noise: [0.5, 0.5, 0.1, 0.15, 0.15, 0.15]
    initial_bias_noise: 0.1

  smartPoseProjectionFactors:
    useSmartPoseProjectionFactor: true
    landmarkDistanceThreshold: -1
    useDegenerateSolutions: false
    dynamicOutlierRejectionThreshold: -1

    defaultPixelNoise: 60.0

    # list of valid types of objects
    objects: [1]
    objectList:
      1_noise: 30

