factorGraphEstimator:
  debug: false
  useImuProp: true
  pipeStdout: true
  isamParameters:
    relinearizeThreshold: 0.01
    relinearizeSkip: 1
    enablePartialRelinearizationCheck: false
    cacheLinearizedFactors: false
    enableDetailedResults: true
    findUnusedFactorSlots: false
    gaussianWildfireThreshold: 0.001

  poseFactorParams:
    usePoseFactor: true
    # rad, rad, rad, m, m, m
    poseNoise: [1.0, 1.0, 1.0, 2.0, 2.0, 2.0]
    poseVelNoise: [2.0, 2.0, 2.0]

  cameraFactorParams:
    useCameraFactor: true
    defaultPixelNoise: 10.0

    landmarkDistanceThreshold: -1
    useDegenerateSolutions: false
    dynamicOutlierRejectionThreshold: -1

    cameraNames: [left_left, left_right, right_left, right_right]

    # list of known objects to track, no - allowed
    objects: [ROS, AIRRLogo, GateCorner]

    ROS_noise: 10
    AIRRLogo_noise: 5
    GateCorner_noise: 10

    left_left:
      # fx, fy, s, u0, v0
      K: [558.27537062177714, 560.17282172757496, 0.0, 604.83688196922208, 313.16185832341853] # mono 0

      # transform x, y, z, qw, qx, qy, qz
      transform: [0.015, 0.18, -0.07, 0.9159759, -0.1205899, -0.3794092, -0.0499494]

    left_right:
      # fx, fy, s, u0, v0
      K: [558.22821956940641, 560.24743342303100, 0.0, 630.09832177799069, 306.71536340731382] # mono 2

      # transform x, y, z, qw, qx, qy, qz
      transform: [0.165, 0.03, -0.07, 0.9159759, -0.1205899, -0.3794092, -0.0499494]

    right_left:
      # fx, fy, s, u0, v0
      K: [554.51459272200827, 555.90737894298354, 0.0, 591.51794469954359, 313.39437257145255] # mono 4

      # transform x, y, z, qw, qx, qy, qz
      transform: [0.165, -0.03, -0.07, 0.9159759, -0.1205899, 0.3794092, 0.0499494]

    right_right:
      # fx, fy, s, u0, v0
      K: [556.65570786523494, 558.86394560254530, 0.0, 622.03565002562493, 326.13390129953063] # mono 5

      # transform x, y, z, qw, qx, qy, qz
      transform: [0.015, -0.18, -0.07, 0.9159759, -0.1205899, 0.3794092, 0.0499494]


  priorConfig:
    # x, y, z, qw, qx, qy, qz, x_dot, y_dot, z_dot
    initial_state: [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    initial_vel_noise: 0.1
    # rad, rad, rad, m, m, m
    initial_pose_noise: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    initial_bias_noise: 0.1

